// Regenerates lib/src/rules/rules_data.dart from rules/*.json so the packs
// ship inside the Dart package with no asset loading.
//
//   dart run tool/embed_rules.dart
import 'dart:io';

void main() {
  final files = Directory('rules')
      .listSync()
      .whereType<File>()
      .where((f) => f.path.endsWith('.json') && !f.path.endsWith('schema.json'))
      .toList()
    ..sort((a, b) {
      // universal first, then regions alphabetically (DocCloak order).
      final ua = a.path.contains('universal') ? 0 : 1;
      final ub = b.path.contains('universal') ? 0 : 1;
      return ua != ub ? ua - ub : a.path.compareTo(b.path);
    });
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/embed_rules.dart - do not edit by hand.')
    ..writeln('// Source: rules/*.json (ported from DocCloak.Core, Apache-2.0).')
    ..writeln()
    ..writeln('/// Raw JSON of every bundled rule pack, keyed by region code,')
    ..writeln('/// universal first.')
    ..writeln('const Map<String, String> bundledRulePackSources = {');
  for (final f in files) {
    final region = f.uri.pathSegments.last.replaceAll('.json', '');
    final content = f.readAsStringSync().trimRight();
    if (content.contains("'''")) {
      throw StateError('${f.path} contains a triple quote');
    }
    out
      ..writeln("  '$region': r'''")
      ..writeln(content)
      ..writeln("''',");
  }
  out.writeln('};');
  File('lib/src/rules/rules_data.dart').writeAsStringSync(out.toString());
  stdout.writeln('Embedded ${files.length} rule packs.');
}
