// Regenerates lib/src/lists/bundled_lists_data.dart from lists/*.json
// (built by tool/fetch_bundled_lists.py at the repository root) so the
// bundled company and place names ship inside the Dart package.
//
//   dart run tool/embed_lists.dart
import 'dart:convert';
import 'dart:io';

void main() {
  final companies = _names('lists/companies.json');
  final places = _names('lists/places_zh.json');
  final out = StringBuffer()
    ..writeln('// GENERATED by tool/embed_lists.dart - do not edit by hand.')
    ..writeln('// Source: lists/*.json (Wikidata, CC0), built by tool/fetch_bundled_lists.py.')
    ..writeln()
    ..writeln('/// Company names (${companies.length}) and Chinese place names')
    ..writeln('/// (${places.length}) bundled with the engine, one JSON array each.')
    ..writeln("const String bundledCompanyNamesJson = r'''")
    ..writeln(jsonEncode(companies))
    ..writeln("''';")
    ..writeln()
    ..writeln("const String bundledPlaceNamesJson = r'''")
    ..writeln(jsonEncode(places))
    ..writeln("''';");
  Directory('lib/src/lists').createSync(recursive: true);
  File('lib/src/lists/bundled_lists_data.dart').writeAsStringSync(out.toString());
  stdout.writeln('Embedded ${companies.length} company names and ${places.length} place names.');
}

List<String> _names(String path) {
  final entries = jsonDecode(File(path).readAsStringSync()) as List<dynamic>;
  final names = <String>{};
  for (final e in entries) {
    names.addAll(((e as Map<String, dynamic>)['names'] as List<dynamic>).cast<String>());
  }
  return names.toList()..sort();
}
